import Foundation
import CoreGraphics

// Mirrors the payload of hexchar-data.json (generated by tools/gen_data.py).
// Keys are single letters to keep the web payload small; the iOS app reuses
// the exact same file.
struct HexEntry: Codable {
    let c: String   // the character itself
    let n: String   // Unicode name, title-cased
    let g: String?  // friendly general-category label
    let m: Int?     // 1 = combining mark (draw on a dotted circle)
    let d: String?  // visible stand-in for characters that draw nothing
    let e: Int?     // 1 = default emoji presentation (draw with U+FE0E)

    var isCombining: Bool { m == 1 }
    var isEmojiDefault: Bool { e == 1 }
}

struct HexCategory: Codable {
    let id: String
    let label: String
    let icon: String
    let chars: [HexEntry]
}

struct HexGroup: Codable {
    let id: String
    let label: String
    let categories: [HexCategory]
}

struct HexData: Codable {
    let unicodeVersion: String
    let groups: [HexGroup]

    var categories: [HexCategory] {
        var out: [HexCategory] = []
        for group in groups { out.append(contentsOf: group.categories) }
        return out
    }

    func groupLabel(forCategoryId id: String) -> String {
        for group in groups {
            for cat in group.categories where cat.id == id { return group.label }
        }
        return ""
    }

    static func load(from url: URL) throws -> HexData {
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(HexData.self, from: data)
    }
}

enum HexUnicode {
    static let dottedCircle = "\u{25CC}"
    static let textPresentation = "\u{FE0E}"

    static func codePoints(_ s: String) -> [String] {
        s.unicodeScalars.map { String(format: "U+%04X", $0.value) }
    }

    static func utf8Hex(_ s: String) -> String {
        Array(s.utf8).map { String(format: "%02X", $0) }.joined(separator: " ")
    }

    static func htmlEntity(_ s: String) -> String {
        s.unicodeScalars.map { String(format: "&#x%X;", $0.value) }.joined()
    }

    static func swiftEscape(_ s: String) -> String {
        s.unicodeScalars.map { String(format: "\\u{%X}", $0.value) }.joined()
    }

    /// What a key should draw (as opposed to what it inserts).
    static func displayText(for entry: HexEntry) -> String {
        if let stand = entry.d { return stand }
        if entry.isCombining { return dottedCircle + entry.c }
        if entry.isEmojiDefault { return entry.c + textPresentation }
        return entry.c
    }

    /// Backspace that removes one whole grapheme cluster before the caret
    /// (a base letter plus everything stacked on it), or the selection.
    /// Offsets are in UTF-16 units, matching UITextView.selectedRange.
    static func deletingBackward(_ text: String, location: Int, length: Int)
        -> (text: String, caret: Int)?
    {
        guard let range = Range(NSRange(location: location, length: length), in: text)
        else { return nil }
        if !range.isEmpty {
            var t = text
            t.removeSubrange(range)
            return (t, location)
        }
        guard range.lowerBound > text.startIndex else { return nil }
        let prev = text.index(before: range.lowerBound)  // one Character = one cluster
        let caret = prev.utf16Offset(in: text)
        var t = text
        t.removeSubrange(prev..<range.lowerBound)
        return (t, caret)
    }
}

enum HexSearch {
    /// Name/code-point search over every entry, mirroring the web app's
    /// scoring: exact char > code point > name prefix > word > substring.
    static func search(_ rawQuery: String, in entries: [HexEntry]) -> [HexEntry] {
        let query = rawQuery.trimmingCharacters(in: .whitespacesAndNewlines)
        let q = query.lowercased()
        if q.isEmpty { return [] }

        var wanted: String? = nil
        let compact = q.replacingOccurrences(of: " ", with: "")
        for prefix in ["u+", "0x", "\\u"] where compact.hasPrefix(prefix) {
            let hex = String(compact.dropFirst(prefix.count))
            if hex.count >= 2, hex.count <= 6, let v = UInt32(hex, radix: 16),
               let scalar = Unicode.Scalar(v) {
                wanted = String(Character(scalar))
            }
        }

        var scored: [(Int, HexEntry)] = []
        for entry in entries {
            let name = entry.n.lowercased()
            var score = 0
            if entry.c == query { score = 1000 }
            else if let w = wanted, entry.c == w { score = 900 }
            else if name == q { score = 800 }
            else if name.hasPrefix(q) { score = 600 - name.count }
            else if name.contains(" " + q) { score = 400 - name.count }
            else if name.contains(q) { score = 200 - name.count }
            if score != 0 { scored.append((score, entry)) }
        }
        scored.sort { $0.0 > $1.0 }
        var out = scored.prefix(300).map { $0.1 }
        if let w = wanted, !out.contains(where: { $0.c == w }) {
            out.insert(HexEntry(c: w, n: "Code Point " + HexUnicode.codePoints(w).joined(),
                                g: nil, m: nil, d: nil, e: nil), at: 0)
        }
        return out
    }
}
