/* HexChar — a honeycomb-packed Unicode keyboard.
   Character data (and its Unicode names) comes from data.js, generated by
   tools/gen_data.py. */
(function () {
  'use strict';

  var DATA = window.HEXCHAR_DATA;
  var $ = function (id) { return document.getElementById(id); };

  var board = document.querySelector('.board');
  var grid = $('grid');
  var textEl = $('text');
  var searchEl = $('search');
  var catsEl = $('cats');
  var titleEl = $('cat-title');
  var countEl = $('cat-count');
  var emptyEl = $('empty');
  var tipEl = $('tip');
  var sheetEl = $('sheet');

  var HEX_SVG = '<svg viewBox="0 0 100 115.47" aria-hidden="true" focusable="false">' +
    '<polygon points="50,2 98,29.9 98,85.6 50,113.5 2,85.6 2,29.9"/></svg>';
  var DOTTED = '◌';            // base for combining marks
  var TEXT_PRESENTATION = '\uFE0E'; // variation selector 15

  var STORE_RECENT = 'hexchar.recents';
  var STORE_FAV = 'hexchar.favorites';
  var MAX_RECENT = 60;

  /* ---------- index ---------- */

  var byChar = Object.create(null); // char -> entry (with .set = category label)
  var allEntries = [];
  var categories = [];              // flat list of real categories

  DATA.groups.forEach(function (group) {
    group.categories.forEach(function (cat) {
      cat.group = group.label;
      categories.push(cat);
      cat.chars.forEach(function (entry) {
        if (!byChar[entry.c]) {
          entry.set = cat.label;
          byChar[entry.c] = entry;
          allEntries.push(entry);
        }
      });
    });
  });

  function entryFor(ch) {
    return byChar[ch] || { c: ch, n: 'Unicode character', set: '—' };
  }

  /* ---------- persisted state ---------- */

  function load(key, fallback) {
    try {
      var raw = localStorage.getItem(key);
      return raw ? JSON.parse(raw) : fallback;
    } catch (e) { return fallback; }
  }
  function save(key, value) {
    try { localStorage.setItem(key, JSON.stringify(value)); } catch (e) { /* private mode */ }
  }

  var recents = load(STORE_RECENT, []).filter(function (c) { return typeof c === 'string'; });
  var favorites = load(STORE_FAV, []).filter(function (c) { return typeof c === 'string'; });

  function isFav(ch) { return favorites.indexOf(ch) !== -1; }

  function toggleFav(ch) {
    var i = favorites.indexOf(ch);
    if (i === -1) favorites.unshift(ch); else favorites.splice(i, 1);
    save(STORE_FAV, favorites);
    Array.prototype.forEach.call(grid.querySelectorAll('.hex'), function (hex) {
      if (hex.dataset.c === ch) hex.classList.toggle('is-fav', isFav(ch));
    });
    return isFav(ch);
  }

  function remember(ch) {
    var i = recents.indexOf(ch);
    if (i !== -1) recents.splice(i, 1);
    recents.unshift(ch);
    if (recents.length > MAX_RECENT) recents.length = MAX_RECENT;
    save(STORE_RECENT, recents);
  }

  /* ---------- code point helpers ---------- */

  function codePoints(str) {
    return Array.from(str).map(function (ch) {
      var hex = ch.codePointAt(0).toString(16).toUpperCase();
      while (hex.length < 4) hex = '0' + hex;
      return 'U+' + hex;
    });
  }

  function utf8Bytes(str) {
    return Array.from(new TextEncoder().encode(str)).map(function (b) {
      var h = b.toString(16).toUpperCase();
      return h.length < 2 ? '0' + h : h;
    }).join(' ');
  }

  function jsEscape(str) {
    return Array.from(str).map(function (ch) {
      var cp = ch.codePointAt(0);
      var hex = cp.toString(16).toUpperCase();
      if (cp > 0xFFFF) return '\\u{' + hex + '}';
      while (hex.length < 4) hex = '0' + hex;
      return '\\u' + hex;
    }).join('');
  }

  function htmlEntity(str) {
    return Array.from(str).map(function (ch) {
      return '&#x' + ch.codePointAt(0).toString(16).toUpperCase() + ';';
    }).join('');
  }

  /* ---------- composer ---------- */

  var segmenter = (typeof Intl !== 'undefined' && Intl.Segmenter)
    ? new Intl.Segmenter(undefined, { granularity: 'grapheme' })
    : null;

  // Start of the grapheme cluster ending at `end`, so backspace removes a
  // letter and everything stacked on it in one go.
  function prevBoundary(value, end) {
    if (end <= 0) return 0;
    if (segmenter) {
      var start = 0;
      var iter = segmenter.segment(value.slice(0, end));
      for (var seg of iter) start = seg.index;
      return start;
    }
    var i = end - 1;
    if (i > 0 && value.charCodeAt(i) >= 0xDC00 && value.charCodeAt(i) <= 0xDFFF) i--;
    return i;
  }

  function replaceRange(str, start, end) {
    textEl.setRangeText(str, start, end, 'end');
    onTextChanged();
  }

  function insert(ch) {
    var start = textEl.selectionStart != null ? textEl.selectionStart : textEl.value.length;
    var end = textEl.selectionEnd != null ? textEl.selectionEnd : start;
    replaceRange(ch, start, end);
    textEl.scrollTop = textEl.scrollHeight;
    remember(ch);
  }

  function backspace() {
    var start = textEl.selectionStart, end = textEl.selectionEnd;
    if (start == null) { textEl.value = ''; onTextChanged(); return; }
    if (start !== end) replaceRange('', start, end);
    else if (start > 0) replaceRange('', prevBoundary(textEl.value, start), start);
  }

  function onTextChanged() {
    var value = textEl.value;
    var points = Array.from(value);
    $('count').textContent = points.length === 0
      ? 'empty'
      : points.length + (points.length === 1 ? ' code point' : ' code points');
    var tail = codePoints(points.slice(-6).join(''));
    $('tail').textContent = tail.join(' ');
  }

  /* ---------- clipboard ---------- */

  var toastTimer = null;
  function toast(message) {
    var el = $('toast');
    el.textContent = message;
    el.hidden = false;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(function () { el.hidden = true; }, 1400);
  }

  function copy(str, label) {
    if (!str) { toast('Nothing to copy'); return; }
    var done = function () { toast(label || 'Copied'); };
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(str).then(done, function () { fallbackCopy(str, done); });
    } else {
      fallbackCopy(str, done);
    }
  }

  function fallbackCopy(str, done) {
    var ta = document.createElement('textarea');
    ta.value = str;
    ta.setAttribute('readonly', '');
    ta.style.position = 'fixed';
    ta.style.opacity = '0';
    document.body.appendChild(ta);
    ta.select();
    try { document.execCommand('copy'); done(); } catch (e) { toast('Copy failed'); }
    document.body.removeChild(ta);
  }

  /* ---------- category bar ---------- */

  var VIRTUAL = [
    { id: 'recent', label: 'Recent', icon: '◴', virtual: true },
    { id: 'favorites', label: 'Favorites', icon: '♡', virtual: true }
  ];

  var state = { catId: 'ipa.vowels', query: '' };

  function buildCatBar() {
    var frag = document.createDocumentFragment();
    VIRTUAL.forEach(function (cat) { frag.appendChild(catButton(cat)); });

    var lastGroup = null;
    categories.forEach(function (cat) {
      if (cat.group !== lastGroup) {
        var sep = document.createElement('span');
        sep.className = 'cat-sep';
        sep.setAttribute('aria-hidden', 'true');
        frag.appendChild(sep);
        lastGroup = cat.group;
      }
      frag.appendChild(catButton(cat));
    });
    catsEl.appendChild(frag);
  }

  function catButton(cat) {
    var b = document.createElement('button');
    b.type = 'button';
    b.className = 'cat';
    b.dataset.id = cat.id;
    b.setAttribute('role', 'tab');
    b.setAttribute('aria-selected', 'false');
    b.title = (cat.group ? cat.group + ' · ' : '') + cat.label;

    var icon = document.createElement('span');
    icon.className = 'cat-icon';
    icon.textContent = cat.icon;
    var label = document.createElement('span');
    label.className = 'cat-label';
    label.textContent = cat.label;

    b.appendChild(icon);
    b.appendChild(label);
    return b;
  }

  function selectCategory(id, scrollIntoView) {
    state.catId = id;
    Array.prototype.forEach.call(catsEl.querySelectorAll('.cat'), function (b) {
      var on = b.dataset.id === id && !state.query;
      b.setAttribute('aria-selected', on ? 'true' : 'false');
      if (on && scrollIntoView && b.scrollIntoView) {
        b.scrollIntoView({ block: 'nearest', inline: 'center' });
      }
    });
    render();
  }

  /* ---------- search ---------- */

  function searchEntries(query) {
    var q = query.trim().toLowerCase();
    if (!q) return [];

    var hex = /^(?:u\+|0x|\\u|\\u\{)?([0-9a-f]{2,6})\}?$/.exec(q.replace(/\s+/g, ''));
    var wanted = hex ? String.fromCodePoint(parseInt(hex[1], 16)) : null;

    var scored = [];
    allEntries.forEach(function (entry) {
      var score = 0;
      var name = entry.n.toLowerCase();
      if (entry.c === query.trim()) score = 1000;
      else if (wanted && entry.c === wanted) score = 900;
      else if (name === q) score = 800;
      else if (name.indexOf(q) === 0) score = 600 - name.length;
      else if (name.indexOf(' ' + q) !== -1) score = 400 - name.length;
      else if (name.indexOf(q) !== -1) score = 200 - name.length;
      else if (entry.set.toLowerCase().indexOf(q) !== -1) score = 100;
      if (score) scored.push([score, entry]);
    });

    // A code point search should still offer the character even when it is
    // not one of the ones this keyboard ships.
    if (wanted && !byChar[wanted] && wanted.trim()) {
      scored.unshift([1100, { c: wanted, n: 'Code point ' + codePoints(wanted)[0], set: 'Search' }]);
    }

    scored.sort(function (a, b) { return b[0] - a[0]; });
    return scored.slice(0, 300).map(function (pair) { return pair[1]; });
  }

  /* ---------- grid ---------- */

  var rowsEls = [];
  var shown = [];

  function currentEntries() {
    if (state.query) return searchEntries(state.query);
    if (state.catId === 'recent') return recents.map(entryFor);
    if (state.catId === 'favorites') return favorites.map(entryFor);
    for (var i = 0; i < categories.length; i++) {
      if (categories[i].id === state.catId) return categories[i].chars;
    }
    return categories[0].chars;
  }

  function heading() {
    if (state.query) return ['Search', shown.length + ' match' + (shown.length === 1 ? '' : 'es')];
    if (state.catId === 'recent') return ['Recent', shown.length ? shown.length + ' characters' : ''];
    if (state.catId === 'favorites') return ['Favorites', shown.length ? shown.length + ' characters' : ''];
    for (var i = 0; i < categories.length; i++) {
      if (categories[i].id === state.catId) {
        return [categories[i].group + ' · ' + categories[i].label,
                categories[i].chars.length + ' characters'];
      }
    }
    return ['', ''];
  }

  function emptyMessage() {
    if (state.query) return 'Nothing matches “' + state.query + '”.';
    if (state.catId === 'recent') return 'Characters you tap show up here.';
    if (state.catId === 'favorites') return 'Long-press a key (or right-click it) to add a favorite.';
    return 'Nothing here.';
  }

  function metrics() {
    var style = getComputedStyle(board);
    var width = board.clientWidth
      - parseFloat(style.paddingLeft) - parseFloat(style.paddingRight);
    var gap = 4;
    var min = width < 380 ? 44 : (width < 620 ? 52 : 58);
    var columns = Math.max(3, Math.floor((width + gap) / (min + gap)));
    var hw = (width + gap) / columns - gap;
    if (hw > 76) { // keep keys thumb-sized rather than enormous on wide screens
      columns = Math.ceil((width + gap) / (76 + gap));
      hw = (width + gap) / columns - gap;
    }
    return { columns: columns, hw: hw, gap: gap };
  }

  function makeHex(entry, row, col) {
    var b = document.createElement('button');
    b.type = 'button';
    b.className = 'hex';
    b.dataset.c = entry.c;
    b.dataset.row = row;
    b.dataset.col = col;
    b.tabIndex = (row === 0 && col === 0) ? 0 : -1;
    b.setAttribute('role', 'gridcell');
    b.setAttribute('aria-label', entry.n);
    b.innerHTML = HEX_SVG;

    var glyph = document.createElement('span');
    glyph.className = 'glyph';
    if (entry.d) {
      glyph.classList.add('label');
      glyph.textContent = entry.d;
    } else if (entry.m) {
      // combining marks need something to sit on: a dimmed dotted circle
      var ring = document.createElement('span');
      ring.className = 'ring';
      ring.textContent = DOTTED;
      glyph.appendChild(ring);
      glyph.appendChild(document.createTextNode(entry.c));
    } else {
      // U+FE0E asks for the text presentation of characters that would
      // otherwise arrive as colour emoji; only the key is drawn that way.
      glyph.textContent = entry.e ? entry.c + TEXT_PRESENTATION : entry.c;
    }
    b.appendChild(glyph);
    if (isFav(entry.c)) b.classList.add('is-fav');
    return b;
  }

  function render() {
    shown = currentEntries();
    var head = heading();
    titleEl.textContent = head[0];
    countEl.textContent = head[1];
    drawGrid();
  }

  function drawGrid() {
    var m = metrics();
    grid.style.setProperty('--hw', m.hw.toFixed(2) + 'px');
    grid.style.setProperty('--gap', m.gap + 'px');
    grid.textContent = '';
    rowsEls = [];

    emptyEl.hidden = shown.length > 0;
    if (!shown.length) {
      emptyEl.textContent = emptyMessage();
      return;
    }

    var frag = document.createDocumentFragment();
    var i = 0, row = 0;
    while (i < shown.length) {
      var odd = row % 2 === 1;
      var take = odd ? m.columns - 1 : m.columns;
      var rowEl = document.createElement('div');
      rowEl.className = 'hex-row' + (odd ? ' odd' : '');
      rowEl.setAttribute('role', 'row');
      var cells = [];
      for (var col = 0; col < take && i < shown.length; col++, i++) {
        var hex = makeHex(shown[i], row, col);
        rowEl.appendChild(hex);
        cells.push(hex);
      }
      frag.appendChild(rowEl);
      rowsEls.push(cells);
      row++;
    }
    grid.appendChild(frag);
  }

  /* ---------- detail sheet ---------- */

  var sheetEntry = null;

  function fact(dl, term, value) {
    var dt = document.createElement('dt');
    dt.textContent = term;
    var dd = document.createElement('dd');
    dd.textContent = value;
    dl.appendChild(dt);
    dl.appendChild(dd);
  }

  function openSheet(entry) {
    sheetEntry = entry;
    $('sheet-glyph').textContent = entry.m ? DOTTED + entry.c
      : (entry.e ? entry.c + TEXT_PRESENTATION : entry.c);
    $('sheet-name').textContent = entry.n;

    var dl = $('sheet-facts');
    dl.textContent = '';
    fact(dl, 'Code point', codePoints(entry.c).join(' '));
    if (entry.g) fact(dl, 'Category', entry.g);
    fact(dl, 'Set', entry.set || '—');
    fact(dl, 'HTML', htmlEntity(entry.c));
    fact(dl, 'JavaScript', jsEscape(entry.c));
    fact(dl, 'UTF-8', utf8Bytes(entry.c));

    var fav = $('sheet-fav');
    fav.textContent = isFav(entry.c) ? '♥ Favorited' : '♡ Favorite';
    fav.setAttribute('aria-pressed', isFav(entry.c) ? 'true' : 'false');

    sheetEl.hidden = false;
    $('sheet-insert').focus();
  }

  function closeSheet() {
    sheetEl.hidden = true;
    sheetEntry = null;
  }

  /* ---------- tooltip ---------- */

  function showTip(hex) {
    var entry = entryFor(hex.dataset.c);
    tipEl.textContent = '';
    var name = document.createElement('b');
    name.textContent = entry.n;
    var cp = document.createElement('span');
    cp.className = 'tip-cp';
    cp.textContent = ' ' + codePoints(entry.c).join(' ');
    tipEl.appendChild(name);
    tipEl.appendChild(cp);
    tipEl.hidden = false;

    var box = hex.getBoundingClientRect();
    var tip = tipEl.getBoundingClientRect();
    var left = Math.min(Math.max(6, box.left + box.width / 2 - tip.width / 2),
                        window.innerWidth - tip.width - 6);
    var top = box.top - tip.height - 8;
    if (top < 6) top = box.bottom + 8;
    tipEl.style.left = left + 'px';
    tipEl.style.top = top + 'px';
  }

  function hideTip() { tipEl.hidden = true; }

  /* ---------- wiring ---------- */

  var pressTimer = null;
  var longPressed = false;

  grid.addEventListener('pointerdown', function (e) {
    var hex = e.target.closest('.hex');
    if (!hex) return;
    longPressed = false;
    hex.classList.add('is-down');
    clearTimeout(pressTimer);
    pressTimer = setTimeout(function () {
      longPressed = true;
      hex.classList.remove('is-down');
      hideTip();
      openSheet(entryFor(hex.dataset.c));
    }, 450);
  });

  ['pointerup', 'pointercancel', 'pointerleave'].forEach(function (type) {
    grid.addEventListener(type, function (e) {
      clearTimeout(pressTimer);
      var hex = e.target.closest && e.target.closest('.hex');
      if (hex) hex.classList.remove('is-down');
    });
  });

  grid.addEventListener('pointermove', function () { clearTimeout(pressTimer); });

  grid.addEventListener('click', function (e) {
    var hex = e.target.closest('.hex');
    if (!hex) return;
    if (longPressed) { longPressed = false; return; }
    insert(hex.dataset.c);
  });

  grid.addEventListener('contextmenu', function (e) {
    var hex = e.target.closest('.hex');
    if (!hex) return;
    e.preventDefault();
    openSheet(entryFor(hex.dataset.c));
  });

  grid.addEventListener('mouseover', function (e) {
    var hex = e.target.closest('.hex');
    if (hex) showTip(hex);
  });
  grid.addEventListener('mouseout', function (e) {
    if (e.target.closest('.hex')) hideTip();
  });
  board.addEventListener('scroll', hideTip);

  // Arrow-key navigation across the honeycomb.
  grid.addEventListener('keydown', function (e) {
    var hex = document.activeElement;
    if (!hex || !hex.classList || !hex.classList.contains('hex')) return;
    var row = +hex.dataset.row, col = +hex.dataset.col;
    var target = null;

    if (e.key === 'ArrowRight') target = (rowsEls[row] || [])[col + 1];
    else if (e.key === 'ArrowLeft') target = (rowsEls[row] || [])[col - 1];
    else if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
      var next = rowsEls[row + (e.key === 'ArrowUp' ? -1 : 1)];
      if (next && next.length) {
        var x = col + (row % 2 ? 1 : 0.5);
        var best = null, bestDist = Infinity;
        next.forEach(function (cell) {
          var cx = +cell.dataset.col + (+cell.dataset.row % 2 ? 1 : 0.5);
          var dist = Math.abs(cx - x);
          if (dist < bestDist) { bestDist = dist; best = cell; }
        });
        target = best;
      }
    } else if (e.key === 'Home') target = (rowsEls[row] || [])[0];
    else if (e.key === 'End') target = (rowsEls[row] || []).slice(-1)[0];
    else return;

    if (target) {
      e.preventDefault();
      hex.tabIndex = -1;
      target.tabIndex = 0;
      target.focus();
      showTip(target);
    }
  });

  catsEl.addEventListener('click', function (e) {
    var cat = e.target.closest('.cat');
    if (!cat) return;
    if (state.query) { searchEl.value = ''; state.query = ''; $('btn-search-clear').hidden = true; }
    selectCategory(cat.dataset.id, true);
    board.scrollTop = 0;
  });

  var searchTimer = null;
  searchEl.addEventListener('input', function () {
    $('btn-search-clear').hidden = !searchEl.value;
    clearTimeout(searchTimer);
    searchTimer = setTimeout(function () {
      state.query = searchEl.value;
      if (!state.query) selectCategory(state.catId, false);
      else {
        Array.prototype.forEach.call(catsEl.querySelectorAll('.cat'), function (b) {
          b.setAttribute('aria-selected', 'false');
        });
        render();
      }
      board.scrollTop = 0;
    }, 90);
  });

  $('btn-search-clear').addEventListener('click', function () {
    searchEl.value = '';
    state.query = '';
    $('btn-search-clear').hidden = true;
    selectCategory(state.catId, false);
    searchEl.focus();
  });

  $('btn-back').addEventListener('click', backspace);
  $('btn-copy').addEventListener('click', function () { copy(textEl.value, 'Text copied'); });
  $('btn-clear').addEventListener('click', function () {
    textEl.value = '';
    onTextChanged();
  });

  textEl.addEventListener('input', onTextChanged);

  $('sheet-close').addEventListener('click', closeSheet);
  $('sheet-insert').addEventListener('click', function () {
    if (sheetEntry) insert(sheetEntry.c);
    closeSheet();
  });
  $('sheet-copy').addEventListener('click', function () {
    if (sheetEntry) copy(sheetEntry.c, 'Character copied');
  });
  $('sheet-fav').addEventListener('click', function () {
    if (!sheetEntry) return;
    var on = toggleFav(sheetEntry.c);
    $('sheet-fav').textContent = on ? '♥ Favorited' : '♡ Favorite';
    $('sheet-fav').setAttribute('aria-pressed', on ? 'true' : 'false');
    if (state.catId === 'favorites' && !state.query) render();
  });
  sheetEl.addEventListener('click', function (e) {
    if (e.target === sheetEl) closeSheet();
  });

  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape') {
      if (!sheetEl.hidden) { closeSheet(); return; }
      if (document.activeElement === searchEl && searchEl.value) {
        $('btn-search-clear').click();
      }
      return;
    }
    var active = document.activeElement;
    var typing = active && /^(INPUT|TEXTAREA)$/.test(active.tagName);
    if (typing) return;
    if (e.key === '/') { e.preventDefault(); searchEl.focus(); }
  });

  var resizeTimer = null;
  window.addEventListener('resize', function () {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(drawGrid, 120);
  });

  /* ---------- go ---------- */

  buildCatBar();
  searchEl.placeholder = 'Search ' + allEntries.length.toLocaleString() +
    ' characters — “schwa”, “arrow”, U+2318';
  onTextChanged();
  selectCategory(recents.length ? 'recent' : 'ipa.vowels', true);
})();
