#!/usr/bin/env python3
"""
Stage 07 - TIMING.md.

Generated from work/analysis.json and work/midi_events.json rather than typed by
hand, so the cue table cannot drift away from the score it documents. Re-run
this whenever stages 02 or 03 are re-run.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
WORK = ROOT / "work"


def tc(t):
    return f"{int(t // 60):02d}:{t % 60:06.3f}"


def barbeat(t, spb, bar_s):
    bar = int(t // bar_s) + 1
    beat = int((t % bar_s) / spb) + 1
    tick = int(round(((t % bar_s) % spb) / spb * 480))
    return f"{bar}.{beat}.{tick:03d}"


def main():
    a = json.loads((WORK / "analysis.json").read_text())
    e = json.loads((WORK / "midi_events.json").read_text())
    spb = e["seconds_per_beat"]
    bar_s = e["bar_seconds"]
    fps = a["fps"]

    L = []
    w = L.append

    w("# TIMING — Mushroom Score")
    w("")
    w("Generated by `src/07_docs.py` from the analysis and MIDI data. Do not edit by hand.")
    w("")
    w("## Source")
    w("")
    w("| | |")
    w("|---|---|")
    w("| clip | `assets/source_IMG_5823.mov` (IMG_5823, iPhone 16 Pro) |")
    w(f"| duration | **{a['duration_s']:.3f} s** ({a['frames']} frames @ {fps:.3f} fps) |")
    w("| render | 720 × 1280, portrait |")
    w(f"| analysis res | {a['analysis_size'][0]} × {a['analysis_size'][1]}, "
      f"flow grid every {a['grid']} px |")
    w("")
    w("## Musical grid")
    w("")
    w("The tempo is **measured, not chosen.** The camera pushes in to maximum zoom twice;")
    w("that interval is treated as one four-bar phrase, so the footage sets the BPM.")
    w("")
    w("| | |")
    w("|---|---|")
    w(f"| tempo | **{e['bpm']:.2f} BPM** |")
    w("| metre | 4/4 |")
    w(f"| beat | {spb:.4f} s |")
    w(f"| bar | {bar_s:.4f} s |")
    w(f"| total | ≈ {a['duration_s'] / bar_s:.2f} bars |")
    w(f"| scale | {e['scale']} |")
    w(f"| PPQ | {e['ticks_per_beat']} |")
    w("")
    w("Bar.beat.tick below is `bar.beat.tick` from the top of the clip, bar 1 beat 1 at 00:00.000.")
    w("")
    w("## Drum cues — the zoom extrema")
    w("")
    w("Every drum hit in the piece is a turning point of the camera's zoom. There are no")
    w("other drum events except the flow-gated hi-hat, which has no fixed positions.")
    w("")
    w("| # | frame | timecode | bar.beat.tick | cue | drums | zoom |")
    w("|---:|---:|---|---|---|---|---:|")
    cues = sorted(
        [(x["frame"], x["t"], "MAX ZOOM IN", "kick 36 + low tom 41", x["zoom"])
         for x in a["zoom_in_extrema"]]
        + [(x["frame"], x["t"], "MAX ZOOM OUT", "crash 49 + snare 38", x["zoom"])
           for x in a["zoom_out_extrema"]])
    for i, (fr, t, kind, drums, z) in enumerate(cues, 1):
        w(f"| {i} | {fr} | `{tc(t)}` | `{barbeat(t, spb, bar_s)}` | **{kind}** | {drums} | {z:.3f} |")
    w("")
    w("## Sections — the stopping points")
    w("")
    w("Each frame is matched in CIELAB against the three reference photographs. A run of")
    w("at least 11 frames (0.37 s) on one stopping point becomes a section; the pad takes")
    w("that section's chord and the bass its root.")
    w("")
    w("| # | stop | in | out | dur | bar.beat.tick | pad | bass |")
    w("|---:|---|---|---|---:|---|---|---|")
    chords = e["chords"]
    bass = {"WIDE": "D1", "MID": "Bb1", "TIGHT": "D2"}
    names = {"WIDE": "Dm (low, open)", "MID": "Bb (bVI)", "TIGHT": "Dm (octave up)"}
    for i, s in enumerate(a["stop_segments"], 1):
        d = s["end_s"] - s["start_s"]
        w(f"| {i} | **{s['stop']}** | `{tc(s['start_s'])}` | `{tc(s['end_s'])}` | "
          f"{d:.2f} s | `{barbeat(s['start_s'], spb, bar_s)}` | "
          f"{names[s['stop']]} {chords[s['stop']]} | {bass[s['stop']]} |")
    w("")
    w("The shape is a double arch — **WIDE → MID → TIGHT → MID → WIDE → MID → TIGHT → MID → WIDE**.")
    w("")
    w("## Continuous mappings")
    w("")
    w("| source | range | destination |")
    w("|---|---|---|")
    w("| zoom curve (apparent cap scale) | 0 → 1 | LEAD pitch, D3–D6 on the pentatonic |")
    w("| optical-flow magnitude | 0 → 1 | LEAD velocity 40–118; hi-hat gate and velocity |")
    w("| plant mask share | 0 → 25 % | CC1 → chorus depth on the lead |")
    w("| frame mean L\\* | 30 → 75 | CC74 → lead filter cutoff, 420 Hz – 6.6 kHz |")
    w("| nearest stopping point | TIGHT/MID/WIDE | pad chord + bass root |")
    w("")
    w("## Sync")
    w("")
    w("* Audio and video share t=0. `out/mushroom_visual_score.mp4` is already muxed.")
    w(f"* The track runs {e['duration_s'] + 2:.2f} s — {a['duration_s']:.2f} s of score")
    w("  plus a ~2 s reverb tail past the last frame. The muxed video is cut to picture")
    w("  with `-shortest`, so the tail is only present in the standalone track.")
    w("* To re-cut against picture, align frame 0 to 00:00.000 and use the frame numbers")
    w("  above; every cue is on an exact source frame, not a quantised grid position.")
    w("")
    w("## Verification")
    w("")
    w(f"* Cap scale vs. optical-flow radial divergence — two independent estimates of the")
    w(f"  same zoom — correlate at **r = {a['capscale_vs_divergence_corr']:+.3f}**.")
    w(f"* CIELAB acceptance radii: mushroom ΔE₀₀ < {a['deltaE2000_radius']['mushroom']:.0f}, "
      f"plant ΔE₀₀ < {a['deltaE2000_radius']['plant']:.0f}.")
    w(f"* Anchors: mushroom L\\*{a['anchor_mushroom_lab'][0]:.2f} "
      f"a\\*{a['anchor_mushroom_lab'][1]:+.2f} b\\*{a['anchor_mushroom_lab'][2]:+.2f}; "
      f"plant L\\*{a['anchor_plant_lab'][0]:.2f} "
      f"a\\*{a['anchor_plant_lab'][1]:+.2f} b\\*{a['anchor_plant_lab'][2]:+.2f}.")
    w("")

    (ROOT / "TIMING.md").write_text("\n".join(L))
    print("wrote", ROOT / "TIMING.md", f"({len(L)} lines)")


if __name__ == "__main__":
    main()
