package main

import (
	"fmt"
	"os"
	"strings"
	"time"
)

// Doc is everything that goes into one $Title.toml.txt file.
type Doc struct {
	Meta     *VideoMeta
	Playlist *Playlist
	Words    []AlignedWord
}

func BuildDoc(meta *VideoMeta, pl *Playlist, words []AlignedWord) *Doc {
	return &Doc{Meta: meta, Playlist: pl, Words: words}
}

// SafeFilename makes a title usable as a filename across platforms.
func SafeFilename(title string) string {
	repl := strings.NewReplacer(
		"/", "-", "\\", "-", ":", " -", "*", "", "?", "", "\"", "'",
		"<", "(", ">", ")", "|", "-", "\x00", "",
	)
	s := strings.TrimSpace(repl.Replace(title))
	if len(s) > 180 {
		s = s[:180]
	}
	if s == "" {
		s = "untitled"
	}
	return s
}

func tomlEscape(s string) string {
	r := strings.NewReplacer(
		"\\", `\\`, "\"", `\"`, "\n", `\n`, "\r", `\r`, "\t", `\t`,
	)
	return r.Replace(s)
}

func tomlStr(s string) string { return `"` + tomlEscape(s) + `"` }

func tomlStrList(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = tomlStr(s)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// EncodeTOML renders the document as TOML. Metadata as top-level tables,
// the aligned transcript as an array of [[transcript.words]] tables, and a
// plain-text rendition at the end for grep-ability.
func EncodeTOML(d *Doc) string {
	var b strings.Builder
	m := d.Meta

	fmt.Fprintf(&b, "# Generated by yt-playlist-transcriber on %s\n",
		time.Now().UTC().Format(time.RFC3339))
	b.WriteString("# Word timings from Gentle (Kaldi) forced alignment, 10 ms frame resolution.\n\n")

	b.WriteString("[video]\n")
	fmt.Fprintf(&b, "id = %s\n", tomlStr(m.ID))
	fmt.Fprintf(&b, "title = %s\n", tomlStr(m.Title))
	fmt.Fprintf(&b, "url = %s\n", tomlStr(m.WebpageURL))
	fmt.Fprintf(&b, "uploader = %s\n", tomlStr(m.Uploader))
	fmt.Fprintf(&b, "channel_id = %s\n", tomlStr(m.ChannelID))
	fmt.Fprintf(&b, "channel_url = %s\n", tomlStr(m.ChannelURL))
	fmt.Fprintf(&b, "upload_date = %s\n", tomlStr(m.UploadDate))
	fmt.Fprintf(&b, "duration_seconds = %g\n", m.Duration)
	fmt.Fprintf(&b, "view_count = %d\n", m.ViewCount)
	fmt.Fprintf(&b, "like_count = %d\n", m.LikeCount)
	fmt.Fprintf(&b, "tags = %s\n", tomlStrList(m.Tags))
	fmt.Fprintf(&b, "categories = %s\n", tomlStrList(m.Categories))
	fmt.Fprintf(&b, "thumbnail = %s\n", tomlStr(m.Thumbnail))
	fmt.Fprintf(&b, "description = %s\n\n", tomlStr(m.Description))

	if d.Playlist != nil {
		b.WriteString("[playlist]\n")
		fmt.Fprintf(&b, "id = %s\n", tomlStr(d.Playlist.ID))
		fmt.Fprintf(&b, "title = %s\n", tomlStr(d.Playlist.Title))
		fmt.Fprintf(&b, "url = %s\n", tomlStr(d.Playlist.URL))
		fmt.Fprintf(&b, "video_count = %d\n\n", len(d.Playlist.Videos))
	}

	if len(d.Words) > 0 {
		b.WriteString("[transcript]\n")
		fmt.Fprintf(&b, "word_count = %d\n", len(d.Words))
		b.WriteString("aligner = \"gentle (kaldi)\"\n")
		b.WriteString("time_unit = \"seconds\"\n\n")
		for _, w := range d.Words {
			b.WriteString("[[transcript.words]]\n")
			fmt.Fprintf(&b, "word = %s\n", tomlStr(w.Word))
			fmt.Fprintf(&b, "start = %.3f\n", w.Start)
			fmt.Fprintf(&b, "end = %.3f\n", w.End)
			fmt.Fprintf(&b, "case = %s\n", tomlStr(w.Case))
			if w.AlignedTo != "" && w.AlignedTo != w.Word {
				fmt.Fprintf(&b, "aligned_word = %s\n", tomlStr(w.AlignedTo))
			}
			b.WriteString("\n")
		}

		plain := make([]string, len(d.Words))
		for i, w := range d.Words {
			plain[i] = w.Word
		}
		b.WriteString("[transcript.plain]\n")
		fmt.Fprintf(&b, "text = %s\n", tomlStr(strings.Join(plain, " ")))
	}

	return b.String()
}

// WriteDoc writes the encoded document to path atomically.
func WriteDoc(path string, d *Doc) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(EncodeTOML(d)), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
