// folk_jim.c — embeds the Jim Tcl bootstrap amalgamation
// (Vendor/jimsh0.c) and exposes the small C API in folk_jim.h.
//
// jimsh0.c is a single-file jimsh generated by jimtcl's
// make-bootstrap-jim (see scripts/fetch-jimtcl.sh). It defines the
// whole Jim core API plus a main(); we rename main away and use the
// embedding API directly.

#include "folk_jim.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define main folk_jimsh0_unused_main
#include "jimsh0.c"
#undef main

static Jim_Interp *g_interp = NULL;
static char *g_result = NULL;
static char g_error[2048];

static void set_error(const char *msg) {
    snprintf(g_error, sizeof g_error, "%s", msg ? msg : "");
}

int folk_init(const char *engine_source) {
    if (g_interp) return 0;
    g_error[0] = '\0';
    if (!engine_source) { set_error("engine_source is NULL"); return -1; }

    Jim_Interp *interp = Jim_CreateInterp();
    if (!interp) { set_error("Jim_CreateInterp failed"); return -1; }
    Jim_RegisterCoreCommands(interp);
    Jim_InitStaticExtensions(interp);

    // Not wanted in an embedded/iOS context: subprocess spawning.
    Jim_Eval(interp, "catch { rename exec {} }");

    if (Jim_Eval(interp, engine_source) != JIM_OK) {
        set_error(Jim_String(Jim_GetResult(interp)));
        Jim_FreeInterp(interp);
        return -1;
    }
    g_interp = interp;
    return 0;
}

// Escape a message into a JSON string body (no surrounding quotes).
static void json_escape_into(char *dst, size_t cap, const char *src) {
    size_t j = 0;
    for (size_t i = 0; src[i] && j + 8 < cap; i++) {
        unsigned char c = (unsigned char)src[i];
        if (c == '"' || c == '\\') {
            dst[j++] = '\\'; dst[j++] = (char)c;
        } else if (c == '\n') {
            dst[j++] = '\\'; dst[j++] = 'n';
        } else if (c < 0x20) {
            j += (size_t)snprintf(dst + j, cap - j, "\\u%04x", c);
        } else {
            dst[j++] = (char)c;
        }
    }
    dst[j] = '\0';
}

const char *folk_eval_program(const char *program_code) {
    static const char *not_ready =
        "{\"ok\":false,\"error\":\"folk_init has not run\",\"statementCount\":0,\"display\":[]}";
    if (!g_interp) return not_ready;
    if (!program_code) program_code = "";

    Jim_Obj *objv[2];
    objv[0] = Jim_NewStringObj(g_interp, "folk-eval-program", -1);
    objv[1] = Jim_NewStringObj(g_interp, program_code, -1);
    Jim_IncrRefCount(objv[0]);
    Jim_IncrRefCount(objv[1]);
    int rc = Jim_EvalObjVector(g_interp, 2, objv);
    Jim_DecrRefCount(g_interp, objv[0]);
    Jim_DecrRefCount(g_interp, objv[1]);

    free(g_result);
    g_result = NULL;

    if (rc != JIM_OK) {
        // folk-eval-program catches program errors itself, so this is
        // an engine bug; surface it as an error frame.
        const char *msg = Jim_String(Jim_GetResult(g_interp));
        set_error(msg);
        char esc[1024];
        json_escape_into(esc, sizeof esc, msg);
        size_t need = strlen(esc) + 128;
        g_result = malloc(need);
        snprintf(g_result, need,
                 "{\"ok\":false,\"error\":\"engine error: %s\",\"statementCount\":0,\"display\":[]}",
                 esc);
    } else {
        g_result = strdup(Jim_String(Jim_GetResult(g_interp)));
    }
    return g_result;
}

const char *folk_last_error(void) {
    return g_error;
}

void folk_teardown(void) {
    if (g_interp) {
        Jim_FreeInterp(g_interp);
        g_interp = NULL;
    }
    free(g_result);
    g_result = NULL;
}
