use crate::qr;
use crate::sources::{escape, Source};
use std::collections::BTreeMap;

/// One works-cited entry as an <li>, with anchor id, full metadata, and a QR to the source.
fn entry(src: &Source) -> String {
    let qr_img = qr::data_uri(&src.url).unwrap_or_default();
    let date = src.date_published.as_deref().unwrap_or("n.d.");
    let license = src.license.as_deref().unwrap_or("license unstated");
    let notes = src
        .notes
        .as_ref()
        .map(|n| format!("<div class=\"notes\">{}</div>", escape(n)))
        .unwrap_or_default();
    let media = src
        .image_url
        .as_ref()
        .map(|u| {
            format!(
                "<div class=\"media-link\">Media: <a href=\"{u}\">direct image</a></div>",
                u = escape(u)
            )
        })
        .unwrap_or_default();
    format!(
        r#"<li class="cite" id="src-{id}">
  <img class="qr" src="{qr}" alt="QR code linking to: {title_attr}" width="76" height="76">
  <div class="body">
    <span class="kind">{kind}</span>
    <span class="title"><a href="{url}">{title}</a></span>
    <div class="meta">{author}. {publisher}, {date}. {license}.</div>
    <div class="alt"><strong>Description:</strong> {alt}</div>
    {media}{notes}
    <div class="accessed">Accessed {accessed} &middot; <span class="url">{url_text}</span></div>
  </div>
</li>"#,
        id = escape(&src.id),
        qr = qr_img,
        title_attr = escape(&src.title),
        kind = escape(&src.kind),
        url = escape(&src.url),
        title = escape(&src.title),
        author = escape(&src.author),
        publisher = escape(&src.publisher),
        date = escape(date),
        license = escape(license),
        alt = escape(&src.alt_text),
        media = media,
        notes = notes,
        accessed = escape(&src.accessed),
        url_text = escape(&src.url),
    )
}

/// The <ol> of all entries — reused verbatim by the standalone page and the
/// mirror embedded at the bottom of index.html.
pub fn list_fragment(sources: &BTreeMap<String, Source>) -> String {
    let items: Vec<String> = sources.values().map(entry).collect();
    format!("<ol class=\"citations\">\n{}\n</ol>", items.join("\n"))
}

pub const CITE_CSS: &str = r#"
ol.citations { list-style: none; padding: 0; margin: 0; counter-reset: cite; }
li.cite {
  display: flex; gap: 1rem; align-items: flex-start;
  padding: 1rem 0.4rem; border-bottom: 1px solid #d8cdb8;
  counter-increment: cite;
}
li.cite::before {
  content: counter(cite, decimal-leading-zero);
  font-family: 'Helvetica Neue', Arial, sans-serif;
  font-size: 0.75rem; color: #b3541e; min-width: 1.6rem; padding-top: 0.2rem;
}
li.cite img.qr { flex: none; border: 1px solid #d8cdb8; background: #fff; padding: 3px; }
li.cite .kind {
  font-family: 'Helvetica Neue', Arial, sans-serif; text-transform: uppercase;
  letter-spacing: 0.14em; font-size: 0.62rem; color: #8a7f6a; display: block;
}
li.cite .title { font-size: 1.02rem; }
li.cite .title a { color: #1e6091; text-decoration: none; }
li.cite .title a:hover { text-decoration: underline; }
li.cite .meta { font-size: 0.85rem; color: #4a4234; margin-top: 0.15rem; }
li.cite .alt { font-size: 0.84rem; margin-top: 0.35rem; }
li.cite .media-link, li.cite .notes { font-size: 0.8rem; color: #6a5f4c; margin-top: 0.3rem; }
li.cite .accessed { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 0.7rem; color: #8a7f6a; margin-top: 0.4rem; }
li.cite .url { word-break: break-all; }
li.cite:target { background: #f3e8cf; outline: 2px solid #b3541e; outline-offset: -2px; }
"#;

pub fn standalone_page(sources: &BTreeMap<String, Source>) -> String {
    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Works Cited — Compute Like Water</title>
<style>
body {{ margin: 0; background: #16130e; font-family: Georgia, serif; color: #241f17; line-height: 1.55; }}
.sheet {{ max-width: 46rem; margin: 0 auto; background: #f5efe2; padding: 2.5rem; min-height: 100vh; }}
h1 {{ font-weight: normal; color: #b3541e; font-size: 1.9rem; margin: 0 0 0.2rem; }}
.sub {{ color: #8a7f6a; font-style: italic; margin-bottom: 1.6rem; }}
.gen {{ font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 0.72rem; color: #8a7f6a; margin-top: 2rem; }}
a {{ color: #1e6091; }}
{cite_css}
</style>
</head>
<body>
<div class="sheet">
<h1>Works Cited</h1>
<p class="sub">Sources for <a href="index.html">&ldquo;Compute Like Water&rdquo;</a> — a talk on electricity,
literacy, and computation as guarded crafts that became rights. Each entry carries a scannable QR code
to the source and the date the medium was accessed.</p>
{list}
<p class="gen">Generated by <code>talkgen cite</code> (Rust) from the <code>sources/</code> folder of JSON records.
Canonical presentation: <a href="index.html">index.html</a>.</p>
</div>
</body>
</html>
"#,
        cite_css = CITE_CSS,
        list = list_fragment(sources),
    )
}
